export default {
  'FACAD-CFT-AAU': [
    'Project',
    'Family',
    'Type',
    'Key',
    'BuiltInCategory',
    'ReportType',
    'KeynoteField',
    'ConstraintField',
    'QuantityField',
  ],
  'FACAD-preCFT-AAU-Key': [
    'Family',
    'Type',
    'Key',
  ],
  'APU-Assign': [
    'Project',
    'Key',
    'Constraint',
    'Description',
    'Unit',
    'Frozen',
    'Estimated',
    'Status',
    'P',
    'Q',
    'ID',
    'ContractorID',
    'Qres',
  ],
};
